" => General Settings --------------------------------------------------------
set number
set relativenumber
set history=1000
set encoding=utf-8
syntax on
" set termguicolors

" show a visual line under the cursor's current line
set cursorline
set smarttab
" Show the 80th char column.
set colorcolumn=80
highlight ColorColumn ctermbg=3
set shiftwidth=4
" => Python Settings ---------------------------------------------------------
let python_highlight_all = 1
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix

" Search Python scripts only
set suffixesadd=.py  
" Ignore pyc files when expanding wildcards
set wildignore=*.pyc 
" Don't show .pyc in file lists
let g:netrw_list_hide= '.*\.pyc$'

" => Plugins ------------------------------------------------------------------
" For Vundle, a vim plugin manager.
set nocompatible            " Forget about VI
filetype off                " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.dotfiles/vim/bundle/Vundle.vim
call vundle#begin('~/.dotfiles/vim/plugins')
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'Yggdroot/indentLine'
Plugin 'SirVer/ultisnips'
" Python Plugins
Plugin 'tmhedberg/SimpylFold'  
Plugin 'skywind3000/asyncrun.vim'
Plugin 'vim-scripts/indentpython.vim'
call vundle#end()            " required
filetype plugin indent on    " required

" => Plugin Settings --------------------------------------------------
" SimplyFold Settings
set foldmethod=indent
set foldlevel=99
" Enable folding with the spacebar
nnoremap <space> za
let g:SimpylFold_docstring_preview = 1
let g:SimpylFold_fold_docstring = 0
" YouCompletMe Settings
let g:ycm_autoclose_preview_window_after_completion = 1
nnoremap <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
" NerdTree Settings
nnoremap <leader>n :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen = 1
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
" Airline Settings
set laststatus=2
set t_Co=256
set noshowmode
" Airline Theme Settings
let g:airline_theme = 'bubblegum'
" indentLine Settings
let g:indentLine_char = '|'
let g:indentLine_showFirstIndentLevel=1
" UltiSnips Settings
let g:UltiSnipsExpandTrigger = "<c-j>"
let g:UltiSnipsJumpForwardTrigger = "<c-j>"
let g:UltiSnipsJumpBackwardTrigger = "<c-k>"
let g:ultisnips_python_style = "google"

" => Customize Python Utils --------------------------------------------------
nnoremap <leader>r :call CompileAndRun()<CR>
nnoremap <leader>s :AsyncStop<CR>

func! CompileAndRun()
	exec "w"
	if &filetype == 'python'
		if search("@profile")
			exec "AsyncRun kernprof -l -v %"
                        exec "copen"
                        exec "wincmd p"
                elseif search("set_trace()")
			exec "!python3 %"
                else
                        exec "AsyncRun -raw python3 %"
                        exec "copen"
                        exec "wincmd p"
                endif
        endif

endfunc

" indent and unindent for NORMAL mode
nnoremap <Tab> >>
nnoremap <S-Tab> <<

